name 'packages-apt'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures packages-apt'
long_description 'Installs/Configures packages-apt'
version '0.1.0'
chef_version '>= 14.0'
